export const SET_PRODUCTS = 'SET_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const SET_EDITABLE_PRODUCT = 'SET_EDITABLE_PRODUCT';
export const SET_VISIBLE_PRODUCT_ADD = 'SET_VISIBLE_PRODUCT_ADD';
export const UNSET_VISIBLE_PRODUCT_ADD = 'UNSET_VISIBLE_PRODUCT_ADD';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
